### PR TITLE
Bug: fix get and post requests

### LINKED ISSUE #14: Bug: fix add and get university post routes
Fix add and get university post routes

### PR DESCRIPTION
**Pull request by ismailkhalil20**
Fix get and post request and test them using postman

Fixes #14

### CODE REVIEW

File: site/controllers/city.js [hunk 1]
```diff
@@ -1,6 +1,12 @@
 const City = require("../models/city");
 
-exports.getUsers = async (req, res, next) => {
+exports.getAddCity = async (req, res, next) => {
```
Comment (martinnajjar12) [inline site/controllers/city.js:3]: Please fix the name of the method, this method is used to get all the cities, why naming it as `getAddCity`?? Plus since we're not using the `req` and `next` parameters, just delete them

File: site/controllers/city.js [hunk 2]
```diff
@@ -1,6 +1,12 @@
...
+  const city = await City.findAll();
+  console.log(req.city);
```
Comment (martinnajjar12) [inline site/controllers/city.js:5]: Delete this `console.log` we don't need it.

File: site/controllers/city.js [hunk 3]
```diff
@@ -1,6 +1,12 @@
...
+  res.send(city);
+};
+
+exports.postAddCity = async (req, res, next) => {
   const city = await City.findAll();
   console.log(req.city);
   res.send(city);
```
Comment (martinnajjar12) [inline site/controllers/city.js:12]: Use `res.json` instead of `res.send`

File: site/controllers/university.js [hunk 4]
```diff
@@ -1,33 +1,25 @@
...
+  const universityName = req.body.university
 
-  City.findOne({ where: { cityName: cityName  } })
-    .then((city) => {
-      console.log(city);
-      if (city) {
-        city.createUniversity({ universityName });
-      } else {
-        const city = City.build({cityName})
+  const [city, created] = await City.findOrCreate({
```
Comment (martinnajjar12) [inline site/controllers/university.js:7]: I'm not a fan of creating a city instance in a university controller.
If the city doesn't exist, then the user should create it first and then create a university that belongs to it.

File: site/controllers/university.js [hunk 5]
```diff
@@ -1,33 +1,25 @@
...
-          res.status(400).send(err);
-        }
-      }
-    })
-    .then((results) => res.json("University is created succesfully"))
-    .catch((err) => console.log(err));
   };
 
-exports.getUniversities = (req, res, next) => {
+exports.getAddUniversity = (req, res, next) => {
```
Comment (martinnajjar12) [inline site/controllers/university.js]: Again here about the naming convention, please use a more proper method name because this method isn't adding any university to the database.

File: site/controllers/university.js [hunk 6]
```diff
@@ -1,33 +1,25 @@
...
   City.findOne({ where: { id: req.body.cityName } })
     .then((city) => city.getUniversity())
-    .then((result) => res.send(result))
+    .then((result) => res.json(result))
     .catch((err) => console.log(err));
```
Comment (martinnajjar12) [inline site/controllers/university.js]: instead of `conosle.log`, you should set the status to 500 and return the error as a json

**Review by martinnajjar12 — CHANGES_REQUESTED** [review]
Thank you for your hard work, please make the changes in order to have a solid application.

File: site/controllers/city.js (hunk 1 above)
Comment (ismailkhalil20) [reply site/controllers/city.js:3]: The goal of this PR is to fix the university controller.

I just added these functions to get the server started, I will fix them in another PR.

File: site/controllers/university.js (hunk 4 above)
Comment (ismailkhalil20) [reply site/controllers/university.js:7]: from what I understand from our meetings the user will have a page for adding a university, so in the backend I will get the city name and university name when submitting the form( if this is not the expected functionality please explain it in our meeting today ).

File: site/controllers/university.js (hunk 6 above)
Comment (ismailkhalil20) [reply site/controllers/university.js]: Thank you for the note, I will fix it.
